# **Task - 1:**


In [ ]:
## Create a Python program that converts between different units of measurement.
def convert_length(n):
    """
        Convert the length based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to meter(1) or feet(2) "))

        if option == 1:
            return n/3.28084
        elif option == 2:
            return n * 3.28084
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_length('abc')}")

# Volumn
def convert_volumn(n):
    """
        Convert the volumn based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to gallon(1) or liter(2) "))

        if option == 1:
            return n/0.219969
        elif option == 2:
            return n * 0.219969
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_volumn(10)}")

# Weight
def convert_weight(n):
    """
        Convert the weight based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to pound(1) or kg(2) "))

        if option == 1:
            return n*2.20462
        elif option == 2:
            return n /2.20462
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_weight(10)}")

Do you want to convert it to meter(1) or feet(2) 1
Cannot perform due to the type issue
None
Do you want to convert it to gallon(1) or liter(2) 1
45.460951315867234
Do you want to convert it to pound(1) or kg(2) 1
22.0462


In [ ]:
# Create a Python program that performs various mathematical operations on a list of numbers.

from re import split
def math_operation():
    try:
        option = int(input("What operation do you want to do today?\n1.Find Max\n2.Find Min\n3.Find Sum\n4.Find Average\n"))
        if option>4 or option<1:
            raise ValueError("Invalid Option")

        numbers = input("Enter the numbers seperated by space: ")
        arr = numbers.split(" ")
        arr = [int(i) for i in arr]

        if(option == 1):
            print(f"The max in the array is: {max(arr)}")
        elif(option == 2):
            print(f"The min in the array is: {min(arr)}")
        elif(option == 3):
            print(f"The sum of numbers in the array is: {add(arr)}")
        elif(option == 4):
            print(f"The average of numbers in the array is: {average(arr)}")

    except ValueError:
        print("Invalid Option Selected")
    except TypeError:
        print("Please input numbers only")

def max(n):
    """
        Returns the maximum number in the list

        parameters:
            n (array of numbers)

        returns:
            max_number
    """
    max_num = n[0]
    for i in range(1,len(n)):
        if max_num < n[i]:
            max_num = n[i]

    return max_num

def min(n):
    """
    Returns the minimum number in the list

    Parameters:
        n (list of numbers)

    Returns:
        min_number
    """
    if not n:  # Check if the list is empty
        raise ValueError("List cannot be empty")

    min_num = n[0]
    for i in range(1, len(n)):
        if min_num > n[i]:
            min_num = n[i]

    return min_num

def add(n):
    """
        Returns the sum of numbers in the list

        parameters:
            n (array of numbers)

        returns:
            max_number
    """
    sum = 0
    for i in range(len(n)):
        sum += n[i]

    return sum

def average(n):
    """
        Returns the average of numbers in the list

        parameters:
            n (array of numbers)

        returns:
            average
    """
    sum = 0
    for i in range(len(n)):
        sum += n[i]

    return sum/len(n)

# begin the program
math_operation()

What operation do you want to do today?
1.Find Max
2.Find Min
3.Find Sum
4.Find Average
1
Enter the numbers seperated by space: 35 3
The max in the array is: 35


# **Exercise on List Manipulation:**

In [ ]:
# Write a Python function that extracts every other element from a list, starting from the first element.

def extract_every_other(lst):
    new_array = []
    for i in range(len(lst)):
        if i%2 != 0: continue
        new_array.append(lst[i])

    return new_array

res = extract_every_other([1,2,3,4,5,6])
print(res)

[1, 3, 5]


In [ ]:
# Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

def get_sublist(lst, start, end):
    return lst[start:end]

res = get_sublist([1,2,3,4,5,6,7], 1,2)
print(res)

[2]


In [ ]:
# Reverse a List Using Slicing
# Write a Python function that reverses a list using slicing.

def reverse_list(lst):
    return lst[::-1]

res = reverse_list([1,2,3,4,5])
print(res)

[5, 4, 3, 2, 1]


In [ ]:
# Remove the First and Last Elements
# Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

def remove_first_last(lst):
    return lst[1:len(lst)-1]

res = remove_first_last([1,2,3,4,5])
print(res)

[2, 3, 4]


In [ ]:
# Get the First n Elements
# Write a Python function that extracts the first n elements from a list.

def get_first_n(lst, n):
    return lst[:n]

res = get_first_n([1,2,3,4,5], 3)
print(res)

[1, 2, 3]


In [ ]:
# Extract Elements from the End
# Write a Python function that extracts the last n elements of a list using slicing.

def get_last_n(lst, n):
    return lst[n:]

res = get_last_n([1,2,3,4,5], 3)
print(res)

[4, 5]


In [ ]:
# Extract Elements in Reverse Order:
# Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

def reverse_skip(lst):
    return lst[::2][::-1]

res = reverse_skip([1,2,3,4,5,6])
print(res)

[5, 3, 1]


# **Exercise on Nested List:**

In [ ]:
# Flatten a Nested List:
# Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

def flatten(lst):
    # List comprehension answer ->
    # return [item for sublist in lst for item in sublist]
    res = []
    for i in lst:
        for j in i:
            res.append(j)

    return res

res = flatten([[1, 2], [3, 4], [5]])
print(res)

[1, 2, 3, 4, 5]


In [ ]:
# Accessing Nested List Elements:
# Write a Python function that extracts a specific element from a nested list given its indices.

def access_nested_element(lst, indices):
    return lst[indices[0]][indices[1]]

res = access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1,2],)
print(res)

6


In [ ]:
# Sum of All Elements in a Nested List:
# Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

def sum_nested(lst):
    # List comprehension answer ->
    # return [item for sublist in lst for item in sublist]
    res = []
    for i in lst:
        for j in i:
            res.append(j)

    return sum(res)

res = sum_nested([[1, 2], [3, 4], [5]])
print(res)

15


In [ ]:
# Remove Specific Element from a Nested List:
# Write a Python function that removes all occurrences of a specific element from a nested list.

def remove_element(lst, elem):
    for i in lst:
        if elem in i:
            i.remove(elem)

    return lst

res = remove_element([[1, 2], [3, 2], [4, 5]], 2)
print(res)

[[1], [3], [4, 5]]


In [ ]:
# Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).

def flatten_list(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]


def find_max(lst):
    return max(flatten_list(lst))

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


In [ ]:
# Count Occurrences of an Element in a Nested List:
# Write a Python function that counts how many times a specific element appears in a nested list.

def count_occurrences(lst, elem):
    f_list = flatten_list(lst)
    return f_list.count(elem)

count_occurrences([[1,2,3],[1,2,3,2]], 2)

3

In [ ]:
# Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

def deep_flatten(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]],))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.


def average_nested(lst):
    temp_arr = deep_flatten(lst)
    return sum(temp_arr)/len(temp_arr)

print(average_nested([[1, 2], [3, [4, 5]], 6]))

3.5


# **To - Do - NumPy**

In [ ]:
# Array Creation:
import numpy as np

# Initialize an empty array with size 2X2.
empty_matrix = np.empty((2,2))
print(empty_matrix)

# Initialize an all one array with size 4X2.
one_matrix = np.ones((4,2))
print(one_matrix)

# Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_arr = np.full((4,2), 2, dtype='float32')

# Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
zeros_like_arr = np.zeros_like(np.array([[1,2],[3,4]]))

# Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_arr = np.ones_like(np.array([1,2,3,4]))

# For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
arr = np.array(new_list)

print(full_arr, zeros_like_arr, ones_arr, arr, sep='\n\n')

[[2.37922954e-316 0.00000000e+000]
 [2.40335822e-316 2.41394151e-316]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]

[[0 0]
 [0 0]]

[1 1 1 1]

[1 2 3 4]


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:

# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
ten_to_fortynine = np.arange(10,49)
print(ten_to_fortynine)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
zero_to_eight = np.arange(0,8)
print(zero_to_eight)

# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
rand_arr = np.random.rand(30).mean()
print("mean: " , rand_arr)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
ten_by_ten = np.random.rand(10,10)
print("max: ", ten_by_ten.max())
print("min: ", ten_by_ten.min())

# 6. Create a zero array of size 10 and replace 5th element with 1.
size_ten = np.zeros((10,1))
size_ten[5] = 1
print(size_ten)

# 7. Reverse an array arr = [1,2,0,0,4,0].
reverse_arr = np.array([1,2,0,0,4,0][::-1])
print(reverse_arr)

# 8. Create a 2d array with 1 on border and 0 inside.
array = np.ones((3, 4))
array[1:-1, 1:-1] = 0
print(array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
eight_by_eight = np.ones((8,8))
eight_by_eight[1::2, ::2] = 0
eight_by_eight[::2, 1::2] = 0
print(eight_by_eight)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[0 1 2 3 4 5 6 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
mean:  0.3303527403206584
max:  0.9972143415635416
min:  0.019011207181054868
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0 4 0 0 2 1]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
# Problem - 3: Array Operations:
# For the following arrays:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

# Complete all the task using numpy:

# 1. Add the two array.
print("ADD: ", x+y)

# 2. Subtract the two array.
print("SUBTRACT: ",x-y)

# 3. Multiply the array with any integers of your choice.
print("SCALAR MULTIPLICATION: ", 3 * x)

# 4. Find the square of each element of the array.
print("SQUARE OF X: ",np.square(x))

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("DOT MULTIPLICATION OF V AND W:",np.dot(v,w))
print("DOT MULTIPLICATION OF X AND V:",np.dot(x,v))
print("DOT MULTIPLICATION OF X AND Y:",np.dot(x,y))

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
print("CONCATENATE X AND Y ALONG ROW: ",np.concatenate((x,y),axis=1))
print("CONCATENATE V AND W: ", np.concatenate((v,w),axis=0))

# {Hint:try np.concatenate() or np.vstack() functions.

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("CONCATENATE X AND V: ", np.concatenate((x,v),axis=0)) # ERROR all the input arrays must have the same shape except in the concatenation axis

ADD:  [[ 6  8]
 [10 13]]
SUBTRACT:  [[-4 -4]
 [-4 -3]]
SCALAR MULTIPLICATION:  [[ 3  6]
 [ 9 15]]
SQUARE OF X:  [[ 1  4]
 [ 9 25]]
DOT MULTIPLICATION OF V AND W: 219
DOT MULTIPLICATION OF X AND V: [29 77]
DOT MULTIPLICATION OF X AND Y: [[19 22]
 [50 58]]
CONCATENATE X AND Y ALONG ROW:  [[1 2 5 6]
 [3 5 7 8]]
CONCATENATE V AND W:  [ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Problem - 4: Matrix Operations:
# For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

# Prove following with Numpy:
# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

# 2. Prove AB = ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)

print((AB == BA).all())

# 3. Prove (AB)T = B(T).A(T)
print((AB.T == np.dot(B.T, A.T)).all())

# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b = np.array([-1,-3,9])
print(np.linalg.solve(A, b))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
False
True
[ 2.  1. -2.]
